### ISSUE TITLE
Exception in thread?

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-workflows#13]
```
Exception in thread StompReceiverThread-1:
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/stomp/transport.py", line 337, in __receiver_loop
    self.process_frame(f, frame)
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/stomp/transport.py", line 188, in process_frame
    self.notify(frame_type, f.headers, f.body)
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/stomp/transport.py", line 241, in notify
    rtn = notify_func(headers, body)
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/workflows/transport/stomp_transport.py", line 396, in _on_message
    target_function(headers, body)
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/workflows/transport/common_transport.py", line 154, in callback_bounce
    callback(header, self._mangle_for_receiving(message))
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/workflows/transport/queue_transport_counterpart.py", line 134, in callback_helper
    'message': cb_message,
  File "/dls_sw/apps/dials/dials-v1-9-0/base/lib/python2.7/site-packages/workflows/frontend/__init__.py", line 232, in send_command
    self._pipe_commands.send(command)
IOError: [Errno 32] Broken pipe
```

**Comment by Anthchirp** [comment]
looks to be solved with current version of dlstbx
